### ISSUE TITLE
Rename BatlabSettings class to CellPlaylist

### ISSUE THREAD

**Issue by stephenrparsons** [Lexcelon/batlab-toolkit-gui#5]
It is more accurate to think of this class as a CellPlaylist that contains both settings for the Batlab (e.g. high voltage cutoff, etc) but also information about a test run that we are calling a cell playlist (e.g. cell names, number of cycles of each type, etc).

We could just rename the class.

Could also break out BatlabSettings into its own class, containing those values that would be fitting (i.e. many but not all of the below):

https://github.com/Lexcelon/batlab-toolkit-gui/blob/5613833bab74760859d19b542277ea4e13ecd166/src/batlabcore/batlabsettings.h#L78-L94

This way, CellPlaylist would contain member variables for the playlist information and then would also have a BatlabSettings member.

But, it might just be simplest to rename the class for now. Open to ideas.

**Comment by hapney** [comment]
@stephenrparsons The way I currently understand it, I believe I am pro separating them into two classes. But I'm also only about 50% sure I fully understand the difference between the two.

**Comment by hapney** [comment]
Although I just spoke to Dan about it, and he thinks that if we store them in the same file, they should be stored in the same class.

**Comment by stephenrparsons** [comment]
I now agree with having them in the same class (and naming it CellPlaylist). Could potentially store the BatlabSettings in their own struct within the class?

**Comment by hapney** [comment]
If we are going to call the class CellPlaylist, I like the idea of storing the BatlabSettings in their own struct. We found a winner! I'll work on that shortly.

**Comment by hapney** [comment]
Do you know which settings in particular are batlab settings or know where I can find that info? Or should I just ask Dan?

**Comment by stephenrparsons** [comment]
Dan :)

**Comment by stephenrparsons** [comment]
Done in above PR
