### ISSUE TITLE
Update button text in debug dialog

### ISSUE THREAD

**Issue by stephenrparsons** [Lexcelon/batlab-toolkit-gui#6]
In the Debug Batlab dialog (Tools -> Debug Batlab), there are "Cancel" and "OK" buttons. These both do the same thing, which is nothing. Any actual actions resulting from that dialog are from the other buttons in it. So it should probably just have one button at the bottom that says "Done" or similar.

**Comment by hapney** [comment]
I feel like "Done" implies a requirement to click it, while "Ok" is like, okay, no more. I just got rid of the "Cancel" button.

**Comment by stephenrparsons** [comment]
@hapney I think you can mention the issue # from the commit and it will automatically close when the commit gets merged, or something?
